<div>
<img src=https://www.institutedata.com/wp-content/uploads/2019/10/iod_h_tp_primary_c.svg width="300">
</div>

1. Compute the scaler product of two vectors

> In mathematics, the dot product or scalar product is an algebraic operation that takes two equal-length sequences of numbers (usually coordinate vectors) and returns a single number. 

> we can calculate it this way:

        a · b = ax × bx + ay × by
        
Hint: [Dot Product](https://www.mathsisfun.com/algebra/vectors-dot-product.html)

In [3]:
import numpy as np
np.dot([-12, 16]), [12, 9])

SyntaxError: unmatched ')' (<ipython-input-3-3ff293a779e5>, line 2)

In [1]:
import numpy as np
a = -12, 16
b = 12, 9
output = np.dot(a, b)
print(output) # scalar always single number

0


In [ ]:
#1
# a · b = ax × bx + ay × by
# = -12 . 12 + 16 . 9
# = -144 + 144 = 0

2. Compute the cross product of two vectors

> When a and b start at the origin point (0,0,0), the Cross Product will end at:

        cx = aybz − azby
        cy = azbx − axbz
        cz = axby − aybx
        
Hint: [Cross Product](https://www.mathsisfun.com/algebra/vectors-cross-product.html)

In [ ]:
#2
x = np.array([[1,2,3], [4,5,6]])
y = np.array([[4,5,6], [1,2,3]])
np.cross(x, y)

In [2]:
import numpy as np
x = np.array([[1,2,3], [4,5,6]])
y = np.array([[4,5,6], [1,2,3]])
np.cross(x, y)



array([[-3,  6, -3],
       [ 3, -6,  3]])

In [5]:
import numpy as np
x = np.array([1,2,3], [4,5,6])
y = np.array([4,5,6], [1,2,3])
output = np.cross(x, y)
print(output)

TypeError: Field elements must be 2- or 3-tuples, got '4'

In [ ]:
# I dont know what's wrong with line 5

3. Compute the Hademard product (entry-wise multiplication) of two vectors.

> In mathematics, the Hadamard product (also known as the Schur product[1] or the entrywise product[2]:ch. 5) is a binary operation that takes two matrices of the same dimensions and produces another matrix of the same dimension as the operands where each element i, j is the product of elements i, j of the original two matrices. It should not be confused with the more common matrix product. It is attributed to, and named after, either French mathematician Jacques Hadamard or German mathematician Issai Schur. [Wiki](https://en.wikipedia.org/wiki/Hadamard_product_(matrices))

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/4eb9bb54b2820fb3583901ec05bc4b474b6d90bc)

In [ ]:
#3
# The Hademard product operates on identically shaped matrices
# and produces a third matrix of the same dimensions.
# Qn: how to draw matrices like above?

# commutative: 3+4 === 4+3 order doesnt matter;





In [ ]:
import numpy as np

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [3]:
np.multiply(a, b)

array([-144,  144])

4. Compute the sum of two matrices.

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/0fb7845af355c550d44020e52699069c044126a9)

In [9]:
4 # Program to add two matrices using nested loop

import numpy as np
x = np.array([[12,7,3], [4 ,5,6], [7 ,8,9]])
y = np.array([[5,8,1], [6,7,3], [4,5,9]])
output = np.dot(x, y)
print(output)

X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

Y = [[5,8,1],
    [6,7,3],
    [4,5,9]]

result = [[17,15,4],
         [10,12,9],
         [11,13,18]]

print(result)

[[114 160  60]
 [ 74  97  73]
 [119 157 112]]
[[17, 15, 4], [10, 12, 9], [11, 13, 18]]


In [10]:
import numpy as np
for f in range(len(X)):
    for g in range(len(Y[0])):
        result[f][g]=X[f][g] + Y[f][g]

    for i in result:
print(i)

IndentationError: expected an indented block (<ipython-input-10-de0b5a665345>, line 7)

In [11]:
import numpy as np
for f in range(len(X)):
    for g in range(len(Y[0])):
        result[f][g]=X[f][g] + Y[f][g]

    for i in result:
    print(i)

IndentationError: expected an indented block (<ipython-input-11-c3a78a73077f>, line 7)

5. Compute the product of two matrices.

![](https://upload.wikimedia.org/wikipedia/commons/e/eb/Matrix_multiplication_diagram_2.svg)

In [15]:
5 # Program to multiply two matrices using nested loops

# 3x3 matrix
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

# 3x4 matrix
Y = [[5,8,1,2],
    [6,7,3,0],
    [4,5,9,1]]

# result is 3x4
result = [[0,0,0,0],
         [0,0,0,0],
         [0,0,0,0]]


In [16]:
for d in range(len(X)):
    for s in range(len(Y[0])):
        for m in range(len(Y)):
            result[d][s] += X[d][m] * Y[m][s]
print()
print(result)
print()
for i in result:
    print(i)
    
np.matmul(X,Y)


[[114, 160, 60, 27], [74, 97, 73, 14], [119, 157, 112, 23]]

[114, 160, 60, 27]
[74, 97, 73, 14]
[119, 157, 112, 23]


array([[114, 160,  60,  27],
       [ 74,  97,  73,  14],
       [119, 157, 112,  23]])

In [17]:
for d in range(len(X)):
    for s in range(len(Y[0])):
        for m in range(len(Y)):
            result[d][s] += X[d][m] * Y[m][s]
print()
print(result)
print()
for i in result:
    print(i)
    
np.matmul(X,Y)


[[228, 320, 120, 54], [148, 194, 146, 28], [238, 314, 224, 46]]

[228, 320, 120, 54]
[148, 194, 146, 28]
[238, 314, 224, 46]


array([[114, 160,  60,  27],
       [ 74,  97,  73,  14],
       [119, 157, 112,  23]])

In [30]:
5 # Program to multiply two matrices using nested loops

# 3x4 matrix
X = [[228, 320, 120, 54],
    [148, 194, 146, 28],
    [238, 314, 224, 46]]

# 3x4 matrix
Y = [[228, 320, 120, 54],
    [148, 194, 146, 28],
    [238, 314, 224, 46],
    
# result is 3x4
result = [[0,0,0,0],
         [0,0,0,0],
         [0,0,0,0]]


SyntaxError: invalid syntax (<ipython-input-30-ca54baedb743>, line 14)

6. Compute the determinant of an n x n matrix.

![](https://integratedmlai.com/wp-content/uploads/2018/12/Matrix_Det_2x2.png)

Hint: [Find the Determinant of a Matrix with Pure Python without Numpy or Scipy](https://integratedmlai.com/find-the-determinant-of-a-matrix-with-pure-python-without-numpy-or-scipy/)

Hint: Use 
> np.linalg.det

In [38]:
# 6
matrix = [[-2,2,-3],[-1,1,3],[2,0,-1]]

import numpy as np
det = np.linalg.det([[-2, 2, 3], [-1, 1, 3], [2 ,0 ,-1]])
print(det)


6.0


In [ ]:
# What went wrong above?

In [32]:
# matrix = [[-2, 2, -3], [-1, 1, 3], [2, 0, -1]]
      ''' a11 a12 a13   a21 a22 a23 a31 a32 a33 '''

    ''' |A| = a11.(a22.a33 - a32.a23) - a12.(a21.a33 - a31.a23) + a13.(a21.a32 - a31.a22) '''

# Rule of Sarrus
det = a11*a22*a33 + a12*a23*a31 + a13*a21*a32 - a31*a22*a13 - a32*a23a11 - a33*a21*a12

IndentationError: unexpected indent (<ipython-input-32-e8c16e84460f>, line 2)

In [37]:
# det = a11*a22*a33 + a12*a23*a31 + a13*a21*a32 - a31*a22*a13 - a32*a23*a11 - a33*a21*a12

det = -2*1*-1 + 2*3*2 + -3*-1*0 - 2*1*-3 - 0*3*-2 - -1*-1*2
det =    2    +   12  +    0    -  -6    -   0    -   2
det = 14 - 8 = 6.0

7. Compute the inverse of an n x n matrix.

For a 3×3 matrix

![](http://mathworld.wolfram.com/images/equations/MatrixInverse/NumberedEquation3.gif)

the matrix inverse is

![](http://mathworld.wolfram.com/images/equations/MatrixInverse/NumberedEquation4.gif)

Hint: Use 
> from numpy.linalg import inv

In [44]:
#7
import numpy as np
a = np.array([[1.0, 2.0], [3.0, 4.0]])
print(np.linalg.inv(a))




[[-2.   1. ]
 [ 1.5 -0.5]]




---



---



> > > > > > > > > © 2021 Institute of Data


---



---



