<div>
<img src=https://www.institutedata.com/wp-content/uploads/2019/10/iod_h_tp_primary_c.svg width="300">
</div>

# Numpy Exploration

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib

# get matplot to show charts inline
%matplotlib inline


In [5]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib

%matplotlib inline

In [6]:
height= np.round(np.random.normal(1.75, 0.20, 7000), 2)
weight= np.round(np.random.normal(60.32, 15, 7000), 2)
population=np.column_stack((height, weight)) 

In [7]:
print('height:\n',height)
print('weight:\n',weight)
print('population:\n',population)

height:
 [1.75 1.9  1.68 ... 1.77 1.84 1.46]
weight:
 [46.14 61.57 59.33 ... 50.39 59.85 46.12]
population:
 [[ 1.75 46.14]
 [ 1.9  61.57]
 [ 1.68 59.33]
 ...
 [ 1.77 50.39]
 [ 1.84 59.85]
 [ 1.46 46.12]]


**1. Find Dimension of Array**

Find dimention of each array: height, weight, population
```
# Expected Ouput
np.ndim(height): 1
np.ndim(weight): 1
np.ndim(population): 2
```

In [9]:
print(np.ndim(height))
print(np.ndim(weight))
print(np.ndim(population))


1
1
2


In [10]:
print('np.ndim(height):', np.ndim(height))
print('np.ndim(weight):', np.ndim(weight))
print('np.ndim(population):', np.ndim(population))


np.ndim(height): 1
np.ndim(weight): 1
np.ndim(population): 2


In [14]:
print('ndim(height):', np.ndim(height))
print('ndim(weight):', np.ndim(weight))
print('ndim(population):', np.ndim(population))



ndim(height): 1
ndim(weight): 1
ndim(population): 2


**2. Find Shape of Array**

Find shape of each array: height, weight, population
```
# Expected Ouput
np.shape(height) : (7000,)
np.shape(weight) : (7000,)
np.shape(population) : (7000, 2)
```



In [15]:
print('np.shape(height):', np.shape(height))
print('np.shape(weight):', np.shape(weight))
print('np.shape(population):', np.shape(population))


np.shape(height): (7000,)
np.shape(weight): (7000,)
np.shape(population): (7000, 2)


**3. Find Size of Array**

Find shape of each array: height, weight, population
```
# Expected Ouput:
np.size(height) : 7000
np.size(weight) : 7000
np.size(weight) : 14000
```



In [13]:
print('np.size(height):', np.size(height))
print('np.size(weight):', np.size(weight))
print('np.size(population):', np.size(population))

np.size(height): 7000
np.size(weight): 7000
np.size(population): 14000


In [ ]:
#--- OK ---

**4. Find Size of Items of Each Array**

Find size of items each array: height, weight, population
```
# Expected Output:
height.itemsize : 8
weight.itemsize : 8
population.itemsize : 8
```

In [19]:
import numpy as np
print('height.itemsize:', np.height.itemsize)
print('weight.itemsize):', np.weight.itemsize)
print('population.itemsize:', np.population.itemsize)

AttributeError: module 'numpy' has no attribute 'height'

In [21]:
print('height.itemsize:', height.itemsize)
print('weight.itemsize):', weight.itemsize)
print('population.itemsize:', population.itemsize)

height.itemsize: 8
weight.itemsize): 8
population.itemsize: 8


In [ ]:
# interesting. You are just printing text and an int

**4. Find Minimum Value of Each Array**

Find minimum value of each array: height, weight, population
```
# Expected Output:
height.min : 1.0
weight.min : 3.24
population.min : 1.0
```



In [22]:
print('height.min():', height.min)
print('weight.min()):', weight.min)
print('population.min():', population.min)

height.min(): <built-in method min of numpy.ndarray object at 0x0000014A41DEDED0>
weight.min()): <built-in method min of numpy.ndarray object at 0x0000014A41DEDAB0>
population.min(): <built-in method min of numpy.ndarray object at 0x0000014A41DED690>


In [23]:
print('height.min():', height.min())
print('weight.min()):', weight.min())
print('population.min():', population.min())

height.min(): 0.99
weight.min()): 3.23
population.min(): 0.99


In [ ]:
#Haha! Tada!

In [ ]:
#BREAK---

**5. Find Maximum Value of Each Array**

Find maximum value of each array: height, weight, population
```
# Expected Output
height.max() : 2.51
weight.max() : 132.17
population.max() : 132.17
```

In [24]:
print('height.max():', height.max())
print('weight.max()):', weight.max())
print('population.max():', population.max())

height.max(): 2.48
weight.max()): 113.71
population.max(): 113.71


**6. Find Mean Value of Each Array**

Find maximum value of each array: height, weight, population
```
# Expected Output
height.mean() : 1.7494871428571428
weight.mean() : 60.41684428571429
population.mean() : 31.083165714285716
```



In [25]:
print('height.mean():', height.mean())
print('weight.mean()):', weight.mean())
print('population.mean():', population.mean())

height.mean(): 1.7491942857142857
weight.mean()): 60.459039999999995
population.mean(): 31.104117142857145


**6. Find Standard Deviation of Each Array**

Find standard deviation value of each array: height, weight, population
```
# Expected Output
height.std() : 0.1981923748970856
weight.std() : 14.821310711612284
population.std() : 31.090684288943482
```

In [26]:
print('height.std():', height.std())
print('weight.std()):', weight.std())
print('population.std():', population.std())

height.std(): 0.1998155062520812
weight.std()): 15.197625430821185
population.std(): 31.260444149673386


**7. Find Total value of Each Array**

Find total value of each array: height, weight, population
```
# Expected Output
height.sum() : 12219.789999999999
weight.sum() : 422009.95
population.sum() : 434229.74
```

In [27]:
print('height.sum():', height.sum())
print('weight.sum()):', weight.sum())
print('population.sum():', population.sum())

height.sum(): 12244.36
weight.sum()): 423213.27999999997
population.sum(): 435457.64


**8. Create a histogram of height and weight**

In [28]:
help(plt.hist)

Help on function hist in module matplotlib.pyplot:

hist(x, bins=None, range=None, density=False, weights=None, cumulative=False, bottom=None, histtype='bar', align='mid', orientation='vertical', rwidth=None, log=False, color=None, label=None, stacked=False, *, data=None, **kwargs)
    Plot a histogram.
    
    Compute and draw the histogram of *x*.  The return value is a tuple
    (*n*, *bins*, *patches*) or ([*n0*, *n1*, ...], *bins*, [*patches0*,
    *patches1*, ...]) if the input contains multiple data.  See the
    documentation of the *weights* parameter to draw a histogram of
    already-binned data.
    
    Multiple data can be provided via *x* as a list of datasets
    of potentially different length ([*x0*, *x1*, ...]), or as
    a 2-D ndarray in which each column is a dataset.  Note that
    the ndarray form is transposed relative to the list form.
    
    Masked arrays are not supported.
    
    The *bins*, *range*, *weights*, and *density* parameters behave as in
    `

**9. Create a boxplot of height and weight**

In [29]:
help(plt.boxplot)

Help on function boxplot in module matplotlib.pyplot:

boxplot(x, notch=None, sym=None, vert=None, whis=None, positions=None, widths=None, patch_artist=None, bootstrap=None, usermedians=None, conf_intervals=None, meanline=None, showmeans=None, showcaps=None, showbox=None, showfliers=None, boxprops=None, labels=None, flierprops=None, medianprops=None, meanprops=None, capprops=None, whiskerprops=None, manage_ticks=True, autorange=False, zorder=None, *, data=None)
    Make a box and whisker plot.
    
    Make a box and whisker plot for each column of *x* or each
    vector in sequence *x*.  The box extends from the lower to
    upper quartile values of the data, with a line at the median.
    The whiskers extend from the box to show the range of the
    data.  Flier points are those past the end of the whiskers.
    
    Parameters
    ----------
    x : Array or a sequence of vectors.
        The input data.
    
    notch : bool, default: False
        Whether to draw a noteched box pl

**10. Create scatterplot of height and weight**

In [31]:
help(plt.scatter)

Help on function scatter in module matplotlib.pyplot:

scatter(x, y, s=None, c=None, marker=None, cmap=None, norm=None, vmin=None, vmax=None, alpha=None, linewidths=None, verts=<deprecated parameter>, edgecolors=None, *, plotnonfinite=False, data=None, **kwargs)
    A scatter plot of *y* vs. *x* with varying marker size and/or color.
    
    Parameters
    ----------
    x, y : float or array-like, shape (n, )
        The data positions.
    
    s : float or array-like, shape (n, ), optional
        The marker size in points**2.
        Default is ``rcParams['lines.markersize'] ** 2``.
    
    c : array-like or list of colors or color, optional
        The marker colors. Possible values:
    
        - A scalar or sequence of n numbers to be mapped to colors using
          *cmap* and *norm*.
        - A 2-D array in which the rows are RGB or RGBA.
        - A sequence of colors of length n.
        - A single color format string.
    
        Note that *c* should not be a single nu



---



---



> > > > > > > > > © 2021 Institute of Data


---



---



